### ISSUE TITLE
topics or word representations

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#11]
Hi :)

where the word representation has been saved. 

How can I see the list of words being extracted from Kate model?

( for the constructing bow I made that and feed to the model as I faced with several error s probably the format of mine was different, I stick with the way yo make using 20_newsgroup) I applied the same for my case. I suppose no problem should  be there as I have almost the same dataset only with one different thing. I have one folder and inside that there are 150K number of documents. so i suppose it should be fine. Im sharing here in case if you think there maybe problem please let me know :) )

Thanks :)

**Comment by saria85** [comment]
Thanks for the quick reply 
I do not have any testing file but I want to see the word representation derived from training phases. so you are saying I should run pred.py script for that, I believe I need to comment out the test function there.

**Comment by hugochan** [comment]
I think you can borrow some code from the word_clouds part in the pred.py file. Basically,  weights = ae.get_weights()[0] will give you the weight matrix from the input layer to the hidden layer. Each row is the word vector of the corresponding word.

**Comment by hugochan** [comment]
I don't know why you got this. Can you tell me what is the number of topics in your experiment?

**Comment by saria85** [comment]
I used 20 topics and this part of your code for saving topics :

```
def train():
    corpus = load_corpus('/home/saria/Downloads/KATE-master/outnews/train.corpus')
    docs, vocab_dict = corpus['docs'], corpus['vocab']
    doc_bow = []
    doc_keys = docs.keys()
    for k in doc_keys:
        bows = []
        for idx, count in docs[k].iteritems():
            bows.append((int(idx), count))
        doc_bow.append(bows)
        del docs[k]
    vocab_dict = dict([(int(y), x) for x, y in vocab_dict.iteritems()])

    n_samples = len(doc_bow)
    doc_bow = np.array(doc_bow)
    np.random.seed(0)
    val_idx = np.random.choice(range(n_samples), 1000, replace=False)
    train_idx = list(set(range(n_samples)) - set(val_idx))
    dbow_train = doc_bow[train_idx].tolist()
    dbow_val = doc_bow[val_idx].tolist()
    del doc_bow

    start = timeit.default_timer()
    lda = train_lda(dbow_train, vocab_dict, 20, 1, 'ldamodel')
    print 'runtime: %ss' % (timeit.default_timer() - start)

    #if args.output:
    doc_keys = np.array(doc_keys)
    generate_doc_codes(lda, dict(zip(doc_keys[train_idx].tolist(), dbow_train)), 'ldaout' + '.train')
    generate_doc_codes(lda, dict(zip(doc_keys[val_idx].tolist(), dbow_val)), 'ldaout' + '.val')
    print 'Saved doc codes file to %s and %s' % ('ldaout' + '.train', 'ldaout' + '.val')


    #if args.save_topics:
    topics_prob = show_topics_prob(lda)
    save_topics_prob(topics_prob, 'ldatopic')
    topics = show_topics(lda)
    write_file(topics, 'ldatopic')
    print 'Saved topics file to %s' % 'ldatopic'

    # if args.calc_distinct:
    #     # mean, std = calc_pairwise_cosine(lda)
    #     # print 'Average pairwise angle (pi): %s (%s)' % (mean / math.pi, std / math.pi)
    #     sd = calc_pairwise_dev(lda)
    #     print 'Average squared deviation from 0 (90 degree): %s' % sd

def save_topics_prob(topics_prob, out_file):
    try:
        with open(out_file, 'w') as datafile:
            for topic in topics_prob:
                datafile.write(' + '.join(["%s * %s" % each for each in topic]) + '\n')
                datafile.write('\n')
    except Exception as e:
        raise e

```

**Comment by saria85** [comment]
still the result is not good, almost the same

**Comment by saria85** [comment]
```
com * 0.554385 + the * 0.451409 + a * 0.318825 + and * 0.307471 + of * 0.268725 + in * 0.228247 + to * 0.18042 + it * 0.144074 + re * 0.119689 + that * 0.104847

for * 0.360047 + newsgroups * 0.151333 + is * 0.148719 + you * 0.143204 + message * 0.138775 + date * 0.130447 + subject * 0.113155 + id * 0.112353 + lines * 0.109283 + path * 0.108057

for * 0.293449 + is * 0.266734 + it * 0.246585 + you * 0.155993 + that * 0.133228 + a * 0.131679 + i * 0.126929 + and * 0.119782 + not * 0.078442 + net * 0.0741323

re * 0.296833 + in * 0.206179 + news * 0.152086 + references * 0.144979 + that * 0.118729 + of * 0.101894 + state * 0.0813979 + s * 0.0761768 + writes * 0.0723365 + the * 0.0702867

cmu * 0.198213 + date * 0.151275 + subject * 0.149176 + message * 0.146396 + cs * 0.13876 + path * 0.138697 + newsgroups * 0.123302 + organization * 0.12244 + id * 0.108876 + cantaloupe * 0.096797

news * 0.160021 + you * 0.121974 + and * 0.107016 + on * 0.0971425 + are * 0.0827083 + s * 0.0785635 + i * 0.073016 + with * 0.0693328 + t * 0.0652548 + if * 0.0614786

in * 0.239678 + re * 0.170185 + references * 0.16849 + i * 0.157229 + on * 0.151873 + writes * 0.15105 + t * 0.134474 + article * 0.118614 + be * 0.0830645 + a * 0.0791227

com * 0.377505 + srv * 0.231452 + re * 0.181949 + message * 0.178917 + id * 0.178625 + newsgroups * 0.17677 + cs * 0.173764 + lines * 0.152223 + subject * 0.150844 + cantaloupe * 0.148212

is * 0.358867 + it * 0.273879 + com * 0.242797 + cmu * 0.167584 + you * 0.109167 + srv * 0.105377 + cs * 0.103204 + eng * 0.0790536 + re * 0.074205 + europa * 0.0729113

i * 0.486748 + to * 0.264548 + it * 0.217767 + and * 0.18013 + is * 0.171668 + a * 0.1366 + re * 0.124011 + edu * 0.0931333 + the * 0.090708 + references * 0.0709081

re * 0.267863 + apr * 0.219515 + com * 0.18826 + you * 0.185358 + organization * 0.183286 + references * 0.165396 + cmu * 0.163906 + it * 0.152491 + path * 0.13907 + state * 0.137503

for * 0.34323 + i * 0.307836 + and * 0.250492 + apr * 0.205373 + of * 0.169213 + a * 0.167521 + you * 0.148115 + in * 0.100028 + s * 0.0997326 + eng * 0.0986318

that * 0.393026 + to * 0.297294 + is * 0.282016 + for * 0.266157 + it * 0.245993 + a * 0.242276 + ohio * 0.241619 + of * 0.237188 + state * 0.231884 + mps * 0.217773

news * 0.266017 + be * 0.187686 + gmt * 0.170472 + organization * 0.109483 + you * 0.107409 + edu * 0.103391 + this * 0.0997311 + on * 0.0907252 + id * 0.0792126 + sender * 0.0671604

net * 0.352136 + re * 0.237158 + com * 0.23227 + references * 0.221057 + is * 0.173642 + posting * 0.165059 + nntp * 0.162741 + host * 0.159953 + it * 0.133949 + a * 0.125126

com * 0.480599 + re * 0.37903 + in * 0.369593 + you * 0.324876 + news * 0.292208 + references * 0.212461 + gmt * 0.142177 + apr * 0.10698 + to * 0.096043 + writes * 0.0918724

state * 0.561135 + ohio * 0.553228 + mps * 0.482766 + zaphod * 0.463298 + com * 0.312048 + i * 0.293845 + this * 0.148828 + for * 0.14363 + apr * 0.130946 + have * 0.118513

com * 0.562857 + from * 0.101163 + srv * 0.100906 + this * 0.0888547 + organization * 0.0852064 + cs * 0.0732601 + cantaloupe * 0.0689833 + eng * 0.0639001 + message * 0.0622215 + gtefsd * 0.0580494

com * 0.288236 + a * 0.126047 + for * 0.121821 + the * 0.0799687 + cs * 0.0644588 + srv * 0.0582934 + date * 0.0559245 + cmu * 0.0514623 + cantaloupe * 0.0373141 + path * 0.0315897

organization * 0.214313 + subject * 0.194078 + newsgroups * 0.173364 + id * 0.168089 + cantaloupe * 0.159998 + date * 0.156607 + path * 0.147653 + it * 0.1443 + cs * 0.127688 + lines * 0.116736


```

**Comment by saria85** [comment]
and these are parameters for making model:
-i corpus.train -nd 20 -ne 100 -bs 100 -nv 1000 -ck 10 -ctype k-comp -sm newsmodel -contr 0.5 --noise gs -o outputnews

**Comment by saria85** [comment]
and it's confusing why some words which are supposed to be deleted in stopped words are still there

**Comment by hugochan** [comment]
-i corpus.train -nd 20 -ne 100 -bs 50 -nv 1000 -ck 6 -ctype kcomp -sm newsmodel  -o outputnews

Please note that -contr and --noise are for contractive ae and denoising ae, respectively.

**Comment by hugochan** [comment]
please check out your vocabulary to see if you remove those stop words.

**Comment by saria85** [comment]
I checked the code and there is stopped words removal, regardin contr and noise, I checked without noise parameters, but for contr, then how this line will be run?
```

ae = AutoEncoder(n_vocab, 20, comp_topk=6, ctype='kcomp', save_model='model')
    ae.fit([X_train_noisy, X_train], [X_val_noisy, X_val], nb_epoch=100, \
            batch_size=50, contractive=6.26)
```

**Comment by saria85** [comment]
sorry my OS has some problem cannot run through terminal thats why Im changing code in IDE so....
I will check all these stuff again tomorrow from the office station. I hope I face logical output :)

**Comment by saria85** [comment]
I deleted most comments as they may be confusing for other people interested in this model.

**Comment by saria85** [comment]
so finally  I run it successfully, now the output is better but still I can see several words like, me,mr, you, your no is been over. do you have any idea whats going on?

Thanks for following up :)

**Comment by saria85** [comment]
this is part of the output on my dataset:
```

nursing * 0.08322038 + disposition * 0.08019203 + caller * 0.0782028 + n * 0.07443094 + key * 0.073535025 + chief * 0.07298546 + transport * 0.07180655 + triage * 0.07174853 + vital * 0.07033803 + nurse * 0.06940902

inr * 0.10238291 + warfarin * 0.0859868 + potential * 0.07237056 + labs * 0.07136836 + target * 0.07040044 + v * 0.07038507 + hgb * 0.06628112 + pharmacist * 0.0653148 + anticoagulation * 0.06398843 + k * 0.06384309

tablet * 0.08195988 + document * 0.07218412 + test * 0.06979004 + caregiver * 0.06628325 + form * 0.065843925 + created * 0.0644942 + information * 0.063139684 + mouth * 0.0614187 + caller * 0.059144933 + instructions * 0.05882454

correct * 0.11844685 + procedure * 0.1125721 + skin * 0.10792388 + procedural * 0.10174813 + consent * 0.10135378 + pause * 0.10052222 + special * 0.0934276 + applicable * 0.092000104 + yes * 0.09144742 + alternatives * 0.09009648

you * 0.06809864 + your * 0.06670986 + no * 0.05721946 + the * 0.053811558 + m * 0.049134687 + is * 0.047527857 + history * 0.04601206 + or * 0.044394653 + in * 0.0436429 + a * 0.043435127

he * 0.03230288 + tube * 0.031661805 + the * 0.024372613 + final * 0.023034802 + his * 0.021631273 + new * 0.020250548 + difficulty * 0.016971054 + catheter * 0.016804064 + mask * 0.01556365 + transferred * 0.014036345

caller * 0.12965485 + communication * 0.11132918 + phone * 0.094939575 + number * 0.09200303 + airway * 0.08847121 + calling * 0.081274875 + technique * 0.079573855 + utilized * 0.07703625 + english * 0.07697081 + tube * 0.07650731
```

**Comment by hugochan** [comment]
Are you able to get decent classification accuracy and visualization after the training?

**Comment by saria85** [comment]
thanks a lot for following up:) 
Actually I finished the training and got the topics. I do not have the labeled data so I can not calculate accuracy.
would you please give me your suggestion:
I have two more step:
1. evaluating of topics
2. finding the similarity between two sets of topic (its very important to me)

for the second case, I have applied your model on the collections of record of patients whom later proved to have Cognitive impairment. Also I have applied on another sets of records of patients whom does not have Cognitive impairment.
So I have two sets of topics. 20 topics for Cognitive impairment and 20 topics for non-Cognitive impairment.

Our goal is to compare these two sets of topics to see which topics has been in Cognitive impairment patients which missed in non-Cognitive Impairment.
I am trying to find the best approach to find the similarity between the vectors of topic of CI and non-CI.
I would like to know your suggestion for this and appreciate taking time.

**Comment by hugochan** [comment]
Hi @saria85 ,

My suggestion is to apply KATE to the whole dataset (including both sets of records). After training the model, you will get a set of topics  and vector representation (strengths of topics) for each record. You can use the record vector as features to train a binary classifier. The learned weights of the classifier will indicate which topics contribute more to the positive class or negative class.

If you want to compute the similarity between two topics, one simple thing to try is to compute the similarity between the corresponding *distributions* over vocabulary.

**Comment by saria85** [comment]
thank you so much for your explanations:)
by this :" The learned weights of the classifier will indicate which topics contribute more to the positive class or negative class", you mean that if there is a word in class1(negative) and the same word in class 2 (positive) of topics, it can predict that the word has more weight in which groups of topics: 1 or 2?

**Comment by hugochan** [comment]
I meant that you can train KATE on the whole dataset. Both positive and negative documents share the same set of topics. And the model will learn representations for all documents. A document vector is basically a *distribution* over the set of topics. A higher value indicates stronger connection between the document and the corresponding topic. On top of the document vectors, you can train a binary classifier to predict document labels. After training the classifier, you might know which topics contribute more to which labels. Image that each topic is one specific feature. You might be able to know which features contribute more to which labels by designing a good classifier.
