### ISSUE TITLE
seeing rare word

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#13]
Hi,

Do you have any idea how can I change the parameters to see more rare words?
I have changed my data set such that I put _ between two words so the result would be word1_word2. kind of bigram in cases I needed them as bigram. when I look at the result I can not see any output in which have the bigram. I was thinking maybe they have not happened in my data set frequently.

Do you have any idea how can I see maybe the more rare word in the output? 
Thanks,
:)

**Comment by hugochan** [comment]
@saria85 Maybe you can first compute the frequency of these bigrams in your raw dataset. I don't understand what the output refers to here.
