### ISSUE TITLE
using sigmoid function

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#16]
Hello again :)

So im now detailing on the approach. 
1. in the last part of the Effect of parameter tuning you discussed that you got the best result with tan function. as your idea was to divide positive and negative neuron and then find the k competitive neuron among the positive and negative ones, how you could examine with sigmoid function?
did you consider range like below 0.5 and above?

**Comment by hugochan** [comment]
@saria85 This is a good question. When testing sigmoid function, I just selected the top k outputs of the sigmoid function.

**Comment by saria85** [comment]
I have one more question regarding the "k_comp_tanh" function.
I have difficulty understanding N = (x - tf.abs(x)) / 2 this part because it will make matrices of zero for negative part. then what will be doing this part?

**Comment by hugochan** [comment]
@saria85 N = (x - tf.abs(x)) / 2 will select the negative components while P = (x + tf.abs(x)) / 2 will select the positive components. We need to handle positive and negative components separately in the K-Comp setting.

**Comment by saria85** [comment]
My mistake, the matrices I gave did not catch the negative part as I did not put negative numbers on it :))
