### ISSUE TITLE
PCA projection plot.

### ISSUE THREAD

**Issue by Somayeh12** [hugochan/KATE#19]
I have trained a model on newsgroup data, now I am trying to plot the pca projection. I tried to run the code plot.py that calls the visualize.py to plot the pca projection, but it doesn't work. If I understand what you exactly you are trying to plot, I could write an script using the results of the training phase, but I couldn't follow the steps in the code. What is the input here? The final document distribution generated from the training phase? how is it a 2D input for pca? I also read your paper, but was't clear in the paper either. I will appreciate if you clarify how to use this.   
for example there are 1108 news documents for the label "comp.sys.mac.hardware" -- after training the model--, should I put all of them  together as a 2D array as one input of PCA and do the same for other labels ?

**Comment by hugochan** [comment]
@Somayeh12 The PCA (or TSNE) algorithm was used to map a high dimensional vector to a 2D vector for better visualization. So the input should be a bunch of document vectors and the output will be corresponding 2D vectors for those documents. Given that, you can plot those 2D document vectors. And you can color those documents differently using the label info in your plot.
