### ISSUE TITLE
UTF 8 - codec can't decode byte

### ISSUE THREAD

**Issue by eliavb** [hugochan/KATE#2]
I am trying to run the preprocess step of 20news on the data downloaded [here](http://www.qwone.com/~jason/20Newsgroups/20news-bydate.tar.gz).

I get the following error:

> $ python construct_20news.py -train 20news/20news-bydate-train/ -test 20news/20news-bydate-test/ -o 20news/out
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xfe in position 1146: invalid start byte

To avoid the issue I replaced this [line](https://github.com/hugochan/KATE/blob/master/autoencoder/preprocessing/preprocessing.py#L94) with the following:

with codecs.open(filename, 'r', encoding='UTF-8', errors='ignore') as fp: 

But then the following steps fail:

> $ python pred.py -i 20news/out/test.corpus -lm 20news/out/model -o 20news/out/output_doc_vec_file -st 20news/out/output_topics -sw 20news/out/output_sample_words -wc 20news/out/output_word_clouds
> Using TensorFlow backend.
> 2017-09-11 15:23:01.788147: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-11 15:23:01.788191: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-11 15:23:01.788199: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-11 15:23:01.788204: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-09-11 15:23:01.788209: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> /usr/local/lib/python2.7/dist-packages/keras/models.py:251: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
>   warnings.warn('No training configuration found in save file: '
> Saved doc codes file to 20news/out/output_doc_vec_file
> Saved topics file to 20news/out/output_topics
> Traceback (most recent call last):
>   File "pred.py", line 162, in <module>
>     main()
>   File "pred.py", line 159, in main
>     test(args)
>   File "pred.py", line 114, in test
>     word_cloud(weights, vocab, queries, save_file=args.word_clouds)
>   File "/usr/local/google/home/eliav/virtual_env/home/kate/KATE-master/autoencoder/testing/visualize.py", line 35, in word_cloud
>     words = [(i, vocab[i]) for i in s]
> KeyError: 'cash'

I guess the two step are connected and the fact that I added an ignore caused the issue.

Thanks in advance,
 Eliav

**Comment by hugochan** [comment]
Hi Eliav,

Actually, the example query words in the code are NOT from 20 Newsgroups, they are from some financial corpus. I guess 'cash' is not in your vocabulary. You can use your own example query words instead.

Hope that helps!
