### ISSUE TITLE
neurons in the middle layer

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#20]
If we consider the latent space say 20, and k =12, then we will have only 12 neurons in the middle layer which is active.
My question is that then when we print our topics in the latent space, does it mean that some of the neurons are already getting shut down so we only have 12 left?

Am I missing something?

**Comment by hugochan** [comment]
@saria85 the k-competition operation is only used in the training phase. You will get 20 topics in the example you gave. To show the topics (i.e., a mix of words), we will need to extract the input-to-hidden weight matrix. You can check out the [code](https://github.com/hugochan/KATE/blob/master/pred.py#L101).

**Comment by saria85** [comment]
Thank you for the explanations, I think I was confused in terms of weight matrix to the latent space, not the output weight matrix.

thank you:)
