### ISSUE TITLE
visualization using pca and tsne

### ISSUE THREAD

**Issue by benam2** [hugochan/KATE#25]
I hope you did not get tired because of my questions, I am almost there:)
Could you let me know how can I visualize the topics as well.

I can see `visualize.py` script, and these argument is necessary:

`doc_codes, doc_labels, classes_to_visual, save_file`

So we already have `doc_codes` and `doc_labels` got it from `predict.py` script.

What do you mean by classes here?
I appreciate your help:)

**Comment by hugochan** [comment]
> I hope you did not get tired because of my questions, I am almost there:)
> Could you let me know how can I visualize the topics as well.
> 
> I can see `visualize.py` script, and these argument is necessary:
> 
> `doc_codes, doc_labels, classes_to_visual, save_file`
> 
> So we already have `doc_codes` and `doc_labels` got it from `predict.py` script.
> 
> What do you mean by classes here?
> I appreciate your help:)

You need document classes for plot document embeddings (i.e., different document types will be plotted in different colors).

I didn't actually visualize topics. I just listed the top words associated to the topics.

**Comment by benam2** [comment]
I can not get how can I get the script run, with this  `python plot.py pathto/20news/train_doc pathto/20news/train.labels pca -o path/20news/vis`.
what is this variable about `bank_year = True`? are you trying to visualize two class `classes_to_visual = ["NF", "F"]`.

if not, do you mind to explain what is your approach here?

Thanks~

**Comment by benam2** [comment]
Could you share which script did you run for plotting the visualization you had in the paper?

**Comment by benam2** [comment]
My visualization has not the same shape as you (I could not get run the code you provided).

by ` I just listed the top words associated to the topics.` do you mean that you use the generated topics rather than using X_docs?

**Comment by hugochan** [comment]
> I can not get how can I get the script run, with this `python plot.py pathto/20news/train_doc pathto/20news/train.labels pca -o path/20news/vis`.
> what is this variable about `bank_year = True`? are you trying to visualize two class `classes_to_visual = ["NF", "F"]`.
> 
> I comment out wherever I felt its not relevant.
> 
> Thanks~

You can just ignore those about banks in plot.py since they are for other datasets. This script is for visualizing document embeddings. To see extracted topics, set the option -st when running pred.py. You will get a list of words associated to each topic.
