### ISSUE TITLE
Sharing the trained models?

### ISSUE THREAD

**Issue by JohnGiorgi** [hugochan/KATE#27]
Hi, 

I was wondering if you could share the trained models presented in the paper for each dataset? (similar to how you have shared the preprocessed data).

This would be immensely useful for anyone who wants to benchmark against your method, as we could effectively just provide the model file to the `-lm` argument of `pred.py`.

**Comment by hugochan** [comment]
Hi,

Thank you for your interest to our work! Unfortunately, we do not have pretrained KATE models now as it has been quite a long time. But you should be able to reproduce the results easily as many others have done. Please let me know if you have any trouble reproducing the results. Thanks!
