### ISSUE TITLE
[Question] Possible to apply in different kinds of data?

### ISSUE THREAD

**Issue by ljvmiranda921** [hugochan/KATE#3]
Hi everyone,

Thank you for answering my question in #1 . Hope you won't mind some of my questions:

1. I would like to ask if this approach is dataset-dependent, meaning, is KATE optimally designed for text data? Does feeding image data, say MNIST. a possible application for this work? 

2. Are there any future research directions regarding the architecture of KATE? 

Thank you again!

**Comment by hugochan** [comment]
Hi,

I appreciate your asking!

1. KATE is not working well on image data. KATE was originally designed for text data to solve the issues such as power-law word distributions. The idea of competition was therefore introduced. I would like to see if graph data will be another possible application.

2. There are many future research directions, e.g., other alternatives to the current competition architecture,  sequential competitive autoencoder, adversarial + competitive autoencoder.

Thanks!

**Comment by TheButlah** [comment]
What sort of experiments were run that indicated it was not good for image data? What were some of the things you observed?

**Comment by hugochan** [comment]
@TheButlah I didn't run extensive experiments. I ran the KATE on the MNIST dataset which did not show promising results. The k-sparse autoencoder even learned better representations than the KATE did on that dataset.
