### ISSUE TITLE
[Question] What is the actual sense of using contractive_loss?

### ISSUE THREAD

**Issue by ser0t0nin** [hugochan/KATE#4]
Hello! Thank you for the availability of the code. I am experimenting with your autoencoder on short russian texts (length up to 128 words, 50k stemmed words in vocabulary, 1.5M texts in the dataset). I can share further results with you if you are interested.

So my question is about using [contractive_loss](https://github.com/hugochan/KATE/blob/master/autoencoder/utils/keras_utils.py#L21-L34). I found it in the code, and it seems like it is really more preferable for me than crossentropy. But i cannot find any mentions about it in the paper. What can you say about it? Did you experiment with it? When it is really more suitable according to your experience? Thanks

**Comment by hugochan** [comment]
Hi,

Thank you for your interest in our work! We did mention contractive autoencoders (CAE) in the paper and compared with them in experiments. CAE did not work well in our experiments. You can find the results in Sec 4.4 in the paper.

**Comment by ser0t0nin** [comment]
Yes, i saw that mention, now understood, thanks. I will dive deeper into CAE now, while reading, i suggested it is a very different network.
