### ISSUE TITLE
[Question] How were word embeddings made if KATE expects a log normalized word count matrix?

### ISSUE THREAD

**Issue by TheButlah** [hugochan/KATE#5]
In the paper you showed nearest neighbor similarity of particular words. How did you do this if the feature vectors that KATE expected were vectors where each index was the log normalized word frequency for a particular document?

**Comment by hugochan** [comment]
We extracted the word embeddings from the input-hidden (word-topic) layer of the KATE. Each input neuron corresponds to a word type, and each hidden neuron corresponds to a virtual topic. The model is expected to learn the interaction between words and topics which can give both topics and word embeddings.

**Comment by TheButlah** [comment]
So you looked at the outputs from the hidden layer (the encoding) and performed K-NN lookup on those? So for example:

> Want to find nearest neighbors for "Dog"
> Dog corresponds to 2nd input neuron
> Hence input to network is one-hot expansion of "2", i.e. [0, 1, 0, 0, ..., 0]
> Encoder layer gives a representation of "Dog" in embedding space i.e. virtual topic space. It is some vector of numbers.
> Use euclidian distance to find which elements of embedding space are closest to the embedded "dog" vector.
> Use decoder layers to convert those embeddings back into words
> Argmax that to give the index of the neuron that is the most active, this corresponds to the decoded word

Is that accurate? Where in the repo is this code? I had some trouble navigating it.

**Comment by hugochan** [comment]
@TheButlah That's not what we did in experiments. After training the model, we extract the input-hidden weight matrix W which is a n by m matrix where n is the vocab size and m is the number of virtual topics. Getting the word embeddings is simply looking up the W. For instance, W[i] gives you the embedding of word type indexed as i in the vocabulary. You can check the get_similar_words function in the pred.py file.

Hope this helps:)

**Comment by TheButlah** [comment]
Is that not functionally equivalent to the following pseudocode?

```
index_of_word = vocab.index('Dog')
one_hot = one_hot(index_of_word)  # Vector shaped [vocab_size]
embedding = matmul(one_hot, W)  # Vector shaped [embedding_size]
```

That is the embedding generated from the one-hot encoding of the word, and I believe it is functionally equivalent to `W[index_of_word]`. Hence our methods are identical (except you don't do the sigmoid function when constructing the embedding, whereas I would originally have done so). Am I correct in this?

**Comment by hugochan** [comment]
@TheButlah What you suggested might give you similar results but they are not equivalent. The way I mentioned does not involve the tanh activation function which you need when doing the encoding and decoding steps. In addition, we compute the cosine similarity between two word vectors.
