### ISSUE TITLE
clustering approach

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#6]
Hello,

Actually I have problem understanding your code. though I was expected to see clustering approach which does not need any label, I can see in part of your code you are trying to create the label for the text data.

I want to apply your code with some modification on health data for my research. I do not have label so I am wondering whether or not this code is helpful for me
It would be appreciated if you can clarify a little bit.

Thanks:)

**Comment by hugochan** [comment]
Hi,

Thank you for your attention! The KATE model is unsupervised so no label is required for training it. In order to verify the quality of learned document embeddings, in our experiments, we conducted text classification tasks where we needed labels for training as well as testing.

**Comment by saria85** [comment]
so you are comparing the result of the classification of your model with LDA which is a pure unlabeled approach?
Its not fair, Isnt?

**Comment by hugochan** [comment]
Hi, that's not true. KATE is purely unsupervised. Just like LDA, KATE itself has nothing to do with classification and it only learns document (and word) embeddings. Document labels were only being used when evaluating the quality of learned embeddings, which is separated from the model.

**Comment by saria85** [comment]
Awesome then you are just using the label data for evaluation part not for the goal of classification.
Great.
I am going to detail on your paper and use your code then.
Do you have any idea or suggestion if I do not have any label data?  Do you think should I consider something while using your code?
I want to evaluate the model by the coherence of the word distribution in each cluster.

**Comment by hugochan** [comment]
I am afraid I won't be able to help much. Because I don't know what your data looks like and what problems you are trying to solve.
