### ISSUE TITLE
justification

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#7]
Also, How can you justify using count of the words as the training should feed to the model?
what if we feed word2vec and then try to make a better representation using this model?

Thanks :)

**Comment by hugochan** [comment]
Hi,

This is an interesting question! The KATE model is supposed to learn good document embeddings from raw text. Specifically, we use Bag-of-Words information of a document. KATE does not rely on other methods such as word2vec. Actually, KATE can also learn word embeddings as demonstrated in the paper.
