### ISSUE TITLE
error in prediction (last line)

### ISSUE THREAD

**Issue by saria85** [hugochan/KATE#9]
hi,

when I run the last line I got this error:

firstly it really will be helpful if you can add an example to each run, for example for the last run what will be sunsitute to [output_word_clouds]?
I just create some empty files and gave the path.

this is the error :

`Using TensorFlow backend.
run k_comp_tanh
WARNING:tensorflow:From /infodev1/home/m193053/PycharmProjects/KATE-master/autoencoder/utils/keras_utils.py:143: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-06-06 10:33:58.571203: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/home/m193053/anaconda3/envs/conda27/lib/python2.7/site-packages/keras/models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Saved doc codes file to /home/m193053/Downloads/out/vecfiles
Saved topics file to /home/m193053/Downloads/out/topics
Traceback (most recent call last):
  File "pred.py", line 162, in <module>
    main()
  File "pred.py", line 159, in main
    test(args)
  File "pred.py", line 114, in test
    word_cloud(weights, vocab, queries, save_file=args.word_clouds)
  File "/infodev1/home/m193053/PycharmProjects/KATE-master/autoencoder/testing/visualize.py", line 35, in word_cloud
    words = [(i, vocab[i]) for i in s]
KeyError: 'interest'
`

and this is what I run:
python pred.py -i /home/m193053/Downloads/out/test.corpus -lm /home/m193053/Downloads/out/model -o /home/m193053/Downloads/out/vecfiles -st /home/m193053/Downloads/out/topics -sw /home/m193053/Downloads/out/words -wc /home/m193053/Downloads/out/clouds

vecfiles, topics, wordsand clouds I create a text file and give the path but I am not sure it is correct way to do.

Thanks for your time :)

**Comment by hugochan** [comment]
Hi,

It was caused by the out-of-vocabulary issue.  We can only plot word clouds for those appearing in the vocabulary. In your case, the word `interest` hard coded in the original script is not part of the vocabulary. You will need to modify the list of words hard coded in the script for plotting word clouds.

**Comment by saria85** [comment]
I am still waiting for a through direction on this :)

**Comment by hugochan** [comment]
Hey @saria85 , your example run looks good. To fix the error you mentioned, you need to modify _queries_ list for plotting word clouds. All the words in the _queries_ list should exist in the vocabulary.
